# Generated by Django 2.2.7 on 2019-12-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='child_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
