# Generated by Django 2.2.7 on 2019-11-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birth',
            old_name='registered_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='birth',
            old_name='registered_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='eligible',
            old_name='is_eligible',
            new_name='birth_id',
        ),
    ]
