# Generated by Django 2.2.7 on 2019-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='entry_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='birth',
            name='registered_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='death',
            name='registered_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
