# Generated by Django 2.2.7 on 2019-11-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='entry_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
