# Generated by Django 2.2.7 on 2019-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0002_auto_20191203_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
    ]
