# Generated by Django 2.2.7 on 2019-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0002_auto_20191219_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='entry_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
