# Generated by Django 2.2.7 on 2019-11-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisystem', '0003_auto_20191121_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='death',
            name='year',
        ),
        migrations.AlterField(
            model_name='birth',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='birth',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
